export const APP_NAME = 'PairUp'
export const BASE_URL = 'http://127.0.0.1:8000/api/v1'
export const ACCESS_TOKEN_KEY = 'pairup.access-token'
export const REFRESH_TOKEN_KEY = 'pairup.refresh-token'
export const CURRENT_USER_KEY = 'pairup.current-user'
export const LOGIN_REDIRECT_KEY = 'pairup.login-redirect'
export const PROFILE_ONBOARDED_KEY = 'pairup.profile-onboarded'
