# Generated by Django 5.2.12 on 2026-04-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_email_verified_at_user_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wechat_openid",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
